AllCops:
  Exclude:
    - 'templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'contur.gemspec'
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'lib/contur/version.rb'

Style/GuardClause:
  Exclude:
    - 'contur.gemspec'
