sudo: required
language: ruby
cache: bundler
services:
- docker
rvm:
- 2.3.1
before_install:
- gem install bundler -v '~> 1.13'
script:
- bundle exec rake install
- bundle exec rake
notifications:
  slack:
    secure: evx296qoaGI0URwE8uPixel9z0SEW0nKHb2v5YS2GeCGsyRTS8/p4io9mKByy5iepz4q4vfZuDGIZKPFSxoss0zZ3YR9hJuyxhhzO1PsEYeGitFjdXj4JQ6ENrltyUFybIs90mVCNcxOMTIPDjlbu38KMEEAAWS7Lqz0moppZxowfruWH90ZxF3GbGbotKDNY9sIV3IWvI3louTn834o4NhBK9vP6uS9V7Utyo9uad/ehWKAg8Z4C1mTbhLOjk+v8BJg7X8/4co/A7WoQTY1H7pi+Xs/ZGPYDVTyeQ4lyy1we5/fRiVf67x6S3DrAAMuaknHD8zbZ1E2VxbEvi3XKWPtjqz/QvCgsbNnyKdXiBbeybe1HXX6sWBNBrxKv4nMQ7D5cZy2CpkKAmpbPgrjKYL3gcHD2M6f7LOMZeWQiyZqG9T0rCtqLqLphFbUflnoyhKBk5elm/hNeRw2i81NuYW4ErFAmjyjWg6K0kazFf6EPPLuMUh5ZJ9ERg4mlK4rkCWc+yy8UEyMRVnvAdP4oAXfPHYQNub1vRBHKx9Vx/JFjSglU9olVNl9uJQLTjvdzZs1tAVEUz4DuMKoYZKOpUJovG3KpX8D6VhHe0CwnFfoMHeVuJ4hs9fUzFD+8L/VGmblVYWvoMF1hlknVK9Wo8L4UZfFWUPB/UTJvuBajVc=
